### ISSUE TITLE
Symfony 3.1

### ISSUE THREAD

**Issue by cdekok** [flint/Lurker#21]
Seems I cannot install lurker because of symfony event 3.1 can you update the requirements in composer.json?

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for henrikbjorn/lurker ^1.1 -> satisfiable by henrikbjorn/lurker[1.1.0].
    - Conclusion: remove symfony/event-dispatcher v3.1.3
    - Conclusion: don't install symfony/event-dispatcher v3.1.3
    - henrikbjorn/lurker 1.1.0 requires symfony/event-dispatcher ~2.2
```

I see it is changed 5 months ago but never tagged?
https://github.com/flint/Lurker/blob/master/composer.json

**Comment by steve-todorov** [comment]
I'm having the same problem. I'm trying to install codegyre/robo which depends on lurker. Any plans for a release?

**Comment by ryden54** [comment]
Same thing here, getting the issue through codegyre/robo which requires lurker

**Comment by ArthurMaroulier** [comment]
Same problem here, we're stuck with symfony 3, robo depends on lurker, have you plan to tag your release ?
Thanks

**Comment by ezzatron** [comment]
Just another vote for a tag. This is causing downstream issues like peridot-php/peridot-watcher-plugin#11
